tnteachershousing/Controllers/InformationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using tnteachershousing.Models;
using PagedList;

namespace tnteachershousing.Controllers
{
    public class InformationController : Controller
    {
        private techearDBContext db = new techearDBContext();
        // GET: Information
        public ActionResult Index(int? page)
        {
            int pagesize = 6;
            var pageNumber = page ?? 1;
            var images = db.gallleryImages.AsNoTracking().OrderBy(i => i.imageID);

            return View(images.ToPagedList(pageNumber,pagesize));
        }

        public ActionResult newsEvent()
        {
            return View();
        }

        public ActionResult our_associate()
        {
            return View();
        }

        public ActionResult Testimonials()
        {
            return View();
        }

        public ActionResult downloads()
        {
            return View();
        }
        public ActionResult faq()
        {
            return View();
        }

        public ActionResult usefullinks()
        {
            return View();
        }

        public ActionResult feedback()
        {
            return View();
        }
        public ActionResult sitemap()
        {
            return View();
        }

        public ActionResult Contact()
        {
            return View();
        }
        // GET: Information/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Information/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Information/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Information/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Information/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Information/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Information/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

tnteachershousing/Controllers/ServiceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace tnteachershousing.Controllers
{
    public class ServiceController : Controller
    {
        // GET: Service
        public ActionResult JointVenture()
        {
            return View();
        }

        public ActionResult ValueAdded()
        {
            return View();
        }
        public ActionResult Land_Survey_and_Feasibility()
        {
            return View();
        }
        public ActionResult Land_Survey_and_Feasibility_enquiry()
        {
            return View();

        }
        public ActionResult loan_support()
        {
            return View();

        }
        public ActionResult loan_support_enquiry()
        {
            return View();

        }

        public ActionResult architectural_design()
        {
            return View();
        }

        public ActionResult architectural_design_enquiry()
        {
            return View();
        }

        public ActionResult construction_support()
        {
            return View();
        }

        public ActionResult construction_support_enquiry()
        {
            return View();
        }

        public ActionResult resell_property()
        {
            return View();
        }

        public ActionResult resell_property_enquiry()
        {
            return View();
        }
        public ActionResult NRI_services()
        {
            return View();
        }

        public ActionResult NRI_services_enquiry()
        {
            return View();
        }



        // GET: Service/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Service/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Service/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Service/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Service/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Service/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Service/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

tnteachershousing/Views/Information/Contact.cshtml
@{
    ViewBag.Title = "Contact us";
    ViewBag.PageInfo = "Contact Us";
}
<style>
   .right_sidebar {
	float: right;
	width: 25%;
	padding: 59px 0px 0px 0px;
}

     .address_info {
	float: left;
	background-color: #f9f9f9;
	border: 1px solid #e1e1e1;
	padding: 20px 20px 10px 20px;
	width: 91%;
	margin-bottom: 40px;
}
.address_info.two {
	background-color: #fff;
	border: none;
	margin-bottom: 20px;
	padding-top: 0px;
}
.content_left {
	float: left;
	width: 71%;
	padding: 59px 0px 0px 0px;
}

.content_right {
	float: right;
	width: 71%;
	padding: 59px 0px 0px 0px;
}

</style>
<div class="clearfix"></div>

<!-- Contant
======================================= -->



<div class="clearfix"></div>

<div class="container ContentHeight">


    <div class="content_left">

        <div class="one_full">
            <script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=false"></script><div style="overflow:hidden;height:300px;width:730px;"><div id="gmap_canvas" class="google-map3" style="height:300px;width:730px;"></div>
            <style>
                #gmap_canvas img {
                    max-width: none !important;
                    background: none !important;
                }
            </style><a class="google-map-code" href="http://premium-wordpress-themes.org" id="get-map-data">design themes</a></div>
            <script type="text/javascript"> function init_map(){var myOptions = {zoom:14,center:new google.maps.LatLng(13.0450227,80.23262620000003),mapTypeId: google.maps.MapTypeId.ROADMAP};map = new google.maps.Map(document.getElementById("gmap_canvas"), myOptions);marker = new google.maps.Marker({map: map,position: new google.maps.LatLng(13.0450227, 80.23262620000003)});infowindow = new google.maps.InfoWindow({content:"<b>Tamilnadu Teachers Housing & Welfare Trust</b><br/>36/1, RAMAKRISHNAPURAM, FIRST FLOOR NORTH USMAN ROAD, T.NAGAR,<br/>600017 chennai" });google.maps.event.addListener(marker, "click", function(){infowindow.open(map,marker);});infowindow.open(map,marker);}google.maps.event.addDomListener(window, 'load', init_map);</script>
        </div>

    </div><!-- end section -->

    <div class="right_sidebar">

        <div class="address_info two">

            <h3>Contact <i>Info</i></h3>
            <!-- <p>Feel free to talk to our online representative at any time you please using our Live Chat system on our website or one of the below instant messaging programs.</p>
             <br /> -->
            <p>Please be patient while waiting for response. (24/7 Support!) <strong>Phone General Inquiries: 91 - 44 - 4909 7777 ( 10 Lines ) </strong></p>
            <!-- <br />
            <h3>Address <i>Info</i></h3> -->
            <ul>
                <li>
                    <strong>TAMILNADU TEACHERS HOUSING & WELFARE TRUST</strong><br />
                    NEW NO: 36/1, RAMAKRISHNAPURAM, FIRST FLOOR<br />
                    NORTH USMAN ROAD, T.NAGAR,<br />
                    CHENNAI - 600017,<br />
                    TAMILNADU,<br />
                    INDIA<br />
                    E-mail: <a href="mailto:wecare@tnteacherstrust.org">wecare@tnteacherstrust.org</a><br />
                    Website: <a href="index.php">www.tnteacherstrust.org</a>
                </li>
            </ul>
            <br />

        </div><!-- end section -->


    </div>

</div>


<div class="clearfix margin_top5"></div>

tnteachershousing/Views/Information/Testimonials.cshtml
@{
    ViewBag.Title = "Testimonials";
    ViewBag.PageInfo = "Testimonials";
}

@section allotment_form
{   
    <link rel="stylesheet" href="@Url.Content("~/Content/assets/js/form/sky-forms.css")" />
    <style>
         .content_fullwidth {
	float: left;
	width: 100%;
	padding: 59px 0px 0px 0px;
}
.content_left {
	float: left;
	width: 71%;
	padding: 59px 0px 0px 0px;
}

.content_right {
	float: right;
	width: 71%;
	padding: 59px 0px 0px 0px;
}

    .right_sidebar {
	float: right;
	width: 25%;
	padding: 59px 0px 0px 0px;
}
    </style>
}


<link rel="stylesheet" href="~/Content/assets/js/form/sky-forms-vas.css" />
<link href="~/Content/assets/css/sumoselect.css" rel="stylesheet" />

<section class="generalwrapper dm-shadow clearfix">
    <div class="container">
        <div class="col-xs-12 pv-10">
        </div>
    </div>
</section>

<section class="generalwrapper dm-shadow clearfix">
    <div class="container">
        <div class="row">

            <div id="content" class="col-lg-8 col-md-8 col-sm-8 col-xs-12 clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 nopad project-box properties-rows clearfix">

                    <!-- <h2 class="section_title_drakgray" style="text-align:center;"><strong>Testimonials</strong></h2> -->
                    <blockquote>
                        <p>The service is excellent and the personnel I worked with were great. No request is out of the question and usually can be accomodated within the current budget and in a reasonable timeframe. Very responsive team and easy company to work with. I enjoy our ongoing partnership.</p>
                    </blockquote>
                    <p style="text-align:right;color:#023267;font-weight:600;">- Mr. Gavaskar, Technical Lead, HCL</p>
                </div>

            </div><!-- end content -->

            <div id="right_sidebar" class="col-lg-4 col-md-4 col-sm4 col-xs-12 clearfix">
                <div class="sidebar_widget">
                    <div class="content_box">
                        <div class="cforms">

                            <form action="/testimonials" method="post" id="sky-form" class="sky-form" enctype="multipart/form-data">
                                <header style="font-size:16px;padding-top: 25px;">Write <strong>Testimonial!</strong></header>
                                <fieldset>
                                    <section>
                                        <label class="label">Name</label>
                                        <label class="input">
                                            <i class="icon-append icon-user"></i>
                                            <input type="text" name="name" id="name" placeholder="Enter your Name">
                                        </label>
                                    </section>
                                    <section>
                                        <label class="label">Profession/Company Name</label>
                                        <label class="input">
                                            <i class="icon-append icon-user"></i>
                                            <input type="text" name="cmp" id="cmp" placeholder="Enter your Company Name">
                                        </label>
                                    </section>
                                    <section>
                                        <label class="label">E-mail</label>
                                        <label class="input">
                                            <i class="icon-append icon-envelope-alt"></i>
                                            <input type="email" name="email" id="email" placeholder="Enter Email Address">
                                        </label>
                                    </section>
                                    <section>
                                        <label class="label">Write Testimonial</label>
                                        <label class="textarea">
                                            <i class="icon-append icon-comment"></i>
                                            <textarea rows="4" name="message" id="message" placeholder="Write Testimonial"></textarea>
                                        </label>
                                    </section>
                                    <section>
                                        <label class="label">Upload Image <small style="font-size:10px; color:#000;">(allows only *.jpg, *.png, *.gif)</small></label>
                                        <label class="file">
                                            <input type="file" name="files" />
                                        </label>
                                    </section>
                                </fieldset>
                                <footer>
                                    <button type="submit" name="smt_testimonial" class="button">Submit Testimonial</button>
                                </footer>
                                <div class="message">
                                    <i class="icon-ok"></i>
                                    <p>Your message was successfully sent!</p>
                                </div>
                            </form>

                        </div>
                    </div>
                </div>

            </div><!-- #right_sidebar -->

        </div><!-- end row -->
    </div><!-- end container -->
</section><!-- end generalwrapper -->}
@section allotement_scripts
{
	<script src="~/Content/assets/js/jquery.sumoselect.js"></script>
	<script type="text/javascript">
		$(document).ready(function () {
			window.asd = $('.SlectBox').SumoSelect({ csvDispCount: 3 });
		});
	</script>
<!-- tabs -->
<script src="~/Content/assets/js/tabs//assets/js/responsive-tabs.min.js" type="text/javascript"></script>

<!-- jquery jcarousel -->
<!-- <script type="text/javascript">
	jQuery(document).ready(function() {
			jQuery('#mycarouselthree').jcarousel();
	});
</script> -->

<!-- accordion -->
<script type="text/javascript" src="~/Content/assets/js/accordion/custom.js"></script>

<script type="text/javascript">
		
	$(function() {
		$("#vas-form").validate(
		{					
			// Rules for form validation
			rules:
			{
				name:
				{
					required: true
				},
				mobile_number:
				{
					required: true,
					minlength: 10,
					digits: true
				},
				email:
				{
					required: true,
					email: true
				},
				message:
				{
					required: true,
					minlength: 10
				},
				copy:
				{
					required: true
				}
			}
		});
		
		
		// Validation
		$("#sky-form").validate(
		{					
			// Rules for form validation
			rules:
			{
				name:
				{
					required: true
				},
				email:
				{
					required: true,
					email: true
				},
				message:
				{
					required: true,
					minlength: 10
				}
			},
								
			// Messages for form validation
			messages:
			{
				name:
				{
					required: 'Please enter your name',
				},
				email:
				{
					required: 'Please enter your email address',
					email: 'Please enter a VALID email address'
				},
				message:
				{
					required: 'Please enter your message'
				}
			}
		});
		
		// Validation		
		$("#enquiryform").validate({					
			// Rules for form validation
			rules:
			{
				name:
				{ required: true },
				phone:
				{	required: true,
					minlength: 10
				},
				email:
				{ required: true,
					email:true
				},
				message:
				{	required: true
				}
			},
			
			// Messages for form validation
			messages:
			{
				name:
				{ required: 'Please enter your name' },
				email:
				{	required: 'Please enter your email address',
					email: 'Please enter a VALID email address'
				},
				phone:
				{	required: 'Please enter your phone number',
					minlength: 'Please enter at least 10 digits'
				},
				message:
				{	required: 'Please enter your message' }
			}
		});
		// Validation
		$("#apply-form").validate(
		{					
			// Rules for form validation
			rules:
			{
				projectId: {required: true},
				siteVist:{required: true},
				interestedIn:{required: true},
				investRange:{required: true},
				timeDuration:{required: true},	
				institution:{required: true},	
				loan_support:{required: true},
				comments:
				{
					required: true,
					minlength: 10
				},
				applicantName:
				{
					required: true,
					minlength: 3
				},
				address:
				{
					required: true,
					minlength: 3
				},
				cityName:
				{
					required: true,
					minlength: 3
				},
				stateName:
				{
					required: true,
					minlength: 3
				},
				countryName:
				{
					required: true,
					minlength: 3
				},
				pinCode:
				{
					required: true,
					minlength: 5,
					digits:true
				},	
				phone:
				{
					required: true,
					minlength: 10,
					digits:true
				},				
				email:
				{
					required: true,
					email: true
				}
			}
		});

		// Validation
		$("#jv-form").validate(
		{					
			// Rules for form validation
			rules:
			{
				ownerName: {
					required: true,
					minlength:3
				},
				mediatorName:{
					required: true,
					minlength:3
				},
				mobileNumber:{
					required: true,
					minlength:10
				},
				areaName:{
					required: true,
					minlength:3
				},
				propertySize:{required: true},	
				address:{
					required: true,
					minlength:5
				},	
				frontAge:{required: true},
				roadWidth:{required: true},
				roadFacingDirections:{required: true},
				intesteredJV:{required: true},
				expectedRation:{required: true},
				askingPrice:{required: true},
				selMetrics:{required: true},
				comments:
				{
					required: true,
					minlength: 10
				},
				propInterested:{required: true}
			}
		});
	});			
</script>
}

tnteachershousing/Views/Information/downloads.cshtml
@{
    ViewBag.Title = "Downloads";
    ViewBag.PageInfo = "Downloads";
}
<style>
    a.but_download {
	padding: 10px 22px 10px 22px;
	margin: 0px 0px 0px 0px;
	background: #ff8100;
	border-bottom: 1px solid #909090;
    color:white;
    font-size:15px;
}
    a.but_download:hover {
	background-color: #ff9900;
    color:black;
    font-size:15px;
    }
    .address_info {
	float: left;
	background-color: #f9f9f9;
	border: 1px solid #e1e1e1;
	padding: 20px 20px 10px 20px;
	width: 91%;
	margin-bottom: 40px;
}
.address_info.two {
	background-color: #fff;
	border: none;
	margin-bottom: 20px;
	padding-top: 0px;
}
.address_info h3 i {
	font-weight: 500;
	font-style: normal;
}

      .info {
            color: #4a84bc;
            border-color: #c6e3ff;
            background-color: #e6f3ff !important;
        }
        .info, .error, .notice, .success {
            -webkit-border-radius: 0px;
            -moz-border-radius: 0px;
            border-radius: 0px;
            border: 1px solid #bbb;
            margin-bottom: 20px;
            font-size: 13px;
        }
        .message-box-wrap {
            border: 0px solid #fff;
            padding: 10px;
        }
        .close-but {
	        width: 10px;
	        height: 10px;
	        float: right;
	        border: none;
	        margin: 5px;
	        cursor: pointer;
	        font-size: 0px;
	        background: url(/Content/images/elements/icon-remove.png) no-repeat center top;
        }
</style>

<section class="generalwrapper dm-shadow clearfix">
    <div class="container">
        <div class="col-xs-12 pv-10">
        </div>
    </div>
</section>

<section class="generalwrapper dm-shadow clearfix">
    <div class="container">
        <div class="row">

            <div id="content" class="col-lg-8 col-md-8 col-sm-8 col-xs-12 clearfix">

                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 nopad project-box properties-rows clearfix">
                    <div id="div1" class="info">
                        <div class="message-box-wrap">
                            <button class="close-but" id="colosebut1">close</button> A various support documents can be downloaded from this page in PDF format. Click specific link to download the file. Expandable Villas / Approved Plots
                        </div>
                    </div>

                    <div style="padding-bottom:20px;margin-bottom:20px;border-bottom:1px dotted #333;">
                        <h5 style="font-size:18px; font-weight:600;">Teachers Edu City Hosur (Near Bangalore) Tamil Nadu</h5>
                        <p>
                            Tamilnadu Teachers Housing Welfare Trust brings you another exiting project for its members under the "Flexible Scheme". The project is launched in Hosur at Kundamaranapalli village that lie inside Tamil Nadu on the Kelangala road and very much reachable to Bangalore. Project has the flexibility to buy plots in Installment and as well as Outright model.  We also have the optional specialized Villa Plots in varieties of 1BHK, 2BHK,and 3 BHK for your choice. Kindly use the download and arrange to submit the filled in applications with Rs.5,000/- Cheque or Demand draft as initial booking advance to participate in the allotment at our Trust office.
                        </p>
                        <p><a href="http://tnteacherstrust.org/downloads/Teachers-Edu-City-Hosur-Nov-2015.pdf" class="but_download" title="Application-Teachers-"><i class="fa fa-download fa-lg"></i> Download File</a><p>
                    </div>
                    <div style="padding-bottom:20px;margin-bottom:20px;border-bottom:1px dotted #333;">
                        <h5 style="font-size:18px; font-weight:600;">Teachers Sri Rajarajeshwari Township Phase-4</h5>
                        <p>
                            Tamilnadu Teachers Housing  Welfare Trust brings you this exiting project for its members under the "Neighbourhood Scheme". The project is reachable through Tirchy-Madurai NH and also via Tirchy-Viralimalai-Pudukkottai road located at Illuppur village. Hundreds of Families are already living in a serene family atmosphere at this Township. We proudly present specialised villa plots, apartments and farm plots in varities of 1BHK,2BHK,and 3 BHK options both available in general and luxury models for your choice. Kindly use the download and arrange to submit the filled in applications with Rs.30,000/- Cheque or Demand draft as initial booking advance to participate in the allotment at our Trust office.
                        </p>
                        <p><a href="http://tnteacherstrust.org/downloads/Teachers-SRR-Township-Application.pdf" class="but_download" title="Application-Trichy-20-08-2015.pdf"><i class="fa fa-download fa-lg"></i> Download File</a><p>
                    </div>

                </div>

            </div><!-- end content -->

            <div id="right_sidebar" class="col-lg-4 col-md-4 col-sm4 col-xs-12 clearfix">
                <div class="address_info two">
                    <h3>Contact <i>Info</i></h3>
                    <p>Please be patient while waiting for response. (24/7 Support!) <strong>Phone General Inquiries: 91 - 44 - 4909 7777 ( 10 Lines ) </strong></p>
                </div><!-- end section -->
            </div><!-- #right_sidebar -->

        </div><!-- end row -->
    </div><!-- end container -->
</section><!-- end generalwrapper -->

tnteachershousing/Views/Information/faq.cshtml
@{
    ViewBag.Title = "FAQ-Frequently asked question";
    ViewBag.PageInfo = "FAQ-Frequently asked question";
}
<style>
     .address_info {
	float: left;
	background-color: #f9f9f9;
	border: 1px solid #e1e1e1;
	padding: 20px 20px 10px 20px;
	width: 91%;
	margin-bottom: 40px;
}
.address_info.two {
	background-color: #fff;
	border: none;
	margin-bottom: 20px;
	padding-top: 0px;
}
.address_info h3 i {
	font-weight: 500;
	font-style: normal;
}

        .content_fullwidth {
	float: left;
	width: 100%;
	padding: 59px 0px 0px 0px;
}
.content_left {
	float: left;
	width: 71%;
	padding: 59px 0px 0px 0px;
}

.content_right {
	float: right;
	width: 71%;
	padding: 59px 0px 0px 0px;
}

    .right_sidebar {
	float: right;
	width: 25%;
	padding: 59px 0px 0px 0px;
}
</style>
<link rel="stylesheet" type="text/css" href="@Url.Content("~/Content/assets/js/tabs/assets/css/responsive-tabs3.css")">

<!-- accordion -->
<link rel="stylesheet" href="@Url.Content("~/Content/assets/js/accordion/accordion.css")" type="text/css" media="all">

<section class="generalwrapper dm-shadow clearfix">
    <div class="container">
        <div class="col-xs-12 pv-10">
        </div>
    </div>
</section>

<section class="generalwrapper dm-shadow clearfix">
    <div class="container ContentHeight">
        <div class="row">

            <div id="content" class="col-lg-8 col-md-8 col-sm-8 col-xs-12 clearfix">

                <div class="accrodation">
                    <!-- section 1 -->
                    <span class="acc-trigger active"><a>Why should I carry out a final inspection on the property I am buying?</a></span>
                    <div class="acc-container">
                        <div class="content">
                            <p>No matter how excited you are about purchasing your new house or unit, it is prudent to undertake a final inspection to ensure that the property is still in the same condition it was when you negotiated the deal.<br /> <br />You should check that all the fixtures and fittings included in the contract are still present and that the previous residents did not cause any damage when moving out of the property.</p>
                        </div>
                    </div>

                </div>

            </div><!-- end content -->

            <div id="right_sidebar" class="col-lg-4 col-md-4 col-sm4 col-xs-12 clearfix">
                <div class="address_info two">
                    <h3>Contact <i>Info</i></h3>
                    <p>Please be patient while waiting for response. (24/7 Support!) <strong>Phone General Inquiries: 91 - 44 - 4909 7777 ( 10 Lines ) </strong></p>
                </div><!-- end section -->
            </div><!-- #right_sidebar -->

        </div><!-- end row -->
    </div><!-- end container -->
</section><!-- end generalwrapper -->

<script type="text/javascript" src="~/Content/assets/js/accordion/custom.js"></script>

tnteachershousing/Views/Information/sitemap.cshtml
@{
    ViewBag.Title = "sitemap";
    ViewBag.PageInfo = "Site map";
}

<style>
    ul.list1 {
        padding-left: 15px;
    }

        ul.list1 li a {
            color: #023267;
            padding: 6px;
        }

            ul.list1 li a:hover {
                color: #fff;
                background: #272727;
                border-radius: 5px;
            }
</style>
<div class="clearfix"></div>

<!-- Contant
======================================= -->



<div class="clearfix"></div>

<div class="container">

    <div class="content_fullwidth">
        <h4><span class="example2"><strong><strong><a href="@Url.Action("index","Home")" >Home</a></strong></strong></span></h4>
        <h4><strong><a href="../About-Us/8/">About Us</a></strong></h4>
        <ul class="list1">
            <li><strong><a href="@Url.Action("overview","Home")">Overview</a></strong></li>
            <li><strong><a href="@Url.Action("mission_statement","Home")">Chairman Message</a></strong></li>
            <li><strong><a href="@Url.Action("management_team","Home")">Management and Team</a></strong></li>
            <li><strong><a href="@Url.Action("core_values","Home")">Core Values</a></strong></li>
        </ul>
        <h4><strong>Projects</strong></h4>
        <ul class="list1">
            <li><strong><a href="@Url.Action("index","Project")">Ongoing</a></strong></li>
            <li><strong><a href="@Url.Action("CompletedProject","Project")">Completed</a></strong></li>
            <li><strong><a href="@Url.Action("AllotmentProcedure","Project")">Allotment Procedure</a></strong></li>
        </ul>
        <h4><strong>Services</strong></h4>
        <ul class="list1">
            <li><strong><a href="@Url.Action("JointVenture","Service")">Joint Ventures</a></strong></li>
            <li><strong><a href="@Url.Action("ValueAdded","Service")">Other Services</a></strong></li>
        </ul>
        <h4><strong><strong><a href="@Url.Action("index","Information")">Gallery</a></strong></strong></h4>
        <h4><strong><strong><a href="@Url.Action("newsEvent","Information")">News &amp; Events</a></strong></strong></h4>
        <h4><strong><strong><a href="@Url.Action("our_associate","Information")">Our Associates</a></strong></strong></h4>
        <h4><strong><strong><a href="@Url.Action("Tetimonials","Information")">Testimonials</a></strong></strong></h4>
        <h4><strong><strong><a href="@Url.Action("downloads","Infomation")">Downloads</a></strong></strong></h4>
        <h4><strong><strong><a href="@Url.Action("faq","Information")">FAQs</a></strong></strong></h4>
        <h4><strong><strong><a href="@Url.Action("usefullinks","Information")">Usefull Links</a></strong></strong></h4>
        <h4><strong><strong><a href="@Url.Action("feedback","information")">Feedback</a></strong></strong></h4>
        <h4><strong><strong><a href="@Url.Action("Contact","Information")">Contact Us</a></strong></strong></h4>
    </div>

</div><!-- end content area -->


<div class="clearfix margin_top7"></div>